version: '3'

services:
  mapcrafter:
    image: skaronator/mapcrafter
    volumes:
      - "config:/config"
      - "output:/output"
      - "world:/world"
    environment:
      THREADS: 4
      RUN_EVERY_SEC: 600